// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AdminAPI is an autogenerated mock type for the AdminAPI type
type AdminAPI struct {
	mock.Mock
}

// AddToken provides a mock function with given fields: token, plugins
func (_m *AdminAPI) AddToken(token string, plugins []string) (interface{}, error) {
	ret := _m.Called(token, plugins)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, []string) interface{}); ok {
		r0 = rf(token, plugins)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(token, plugins)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllowToken provides a mock function with given fields: token, plugins
func (_m *AdminAPI) AllowToken(token string, plugins []string) (interface{}, error) {
	ret := _m.Called(token, plugins)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, []string) interface{}); ok {
		r0 = rf(token, plugins)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(token, plugins)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisallowToken provides a mock function with given fields: token, plugins
func (_m *AdminAPI) DisallowToken(token string, plugins []string) (interface{}, error) {
	ret := _m.Called(token, plugins)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, []string) interface{}); ok {
		r0 = rf(token, plugins)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = rf(token, plugins)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSessions provides a mock function with given fields:
func (_m *AdminAPI) ListSessions() (interface{}, error) {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTokens provides a mock function with given fields:
func (_m *AdminAPI) ListTokens() (interface{}, error) {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveToken provides a mock function with given fields: token
func (_m *AdminAPI) RemoveToken(token string) (interface{}, error) {
	ret := _m.Called(token)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
