// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Composites       string
	CompositesRooms  string
	DynamicConfig    string
	Gateways         string
	RoomStatistics   string
	Rooms            string
	SchemaMigrations string
	Sessions         string
	Users            string
}{
	Composites:       "composites",
	CompositesRooms:  "composites_rooms",
	DynamicConfig:    "dynamic_config",
	Gateways:         "gateways",
	RoomStatistics:   "room_statistics",
	Rooms:            "rooms",
	SchemaMigrations: "schema_migrations",
	Sessions:         "sessions",
	Users:            "users",
}
