// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Composites", testCompositesUpsert)

	t.Run("CompositesRooms", testCompositesRoomsUpsert)

	t.Run("Gateways", testGatewaysUpsert)

	t.Run("Rooms", testRoomsUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Sessions", testSessionsUpsert)

	t.Run("Users", testUsersUpsert)
}
