// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRooms(t *testing.T) {
	t.Parallel()

	query := Rooms()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRoomsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRoomsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Rooms().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRoomsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RoomSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRoomsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RoomExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Room exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RoomExists to return true, but got false.")
	}
}

func testRoomsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	roomFound, err := FindRoom(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if roomFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRoomsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Rooms().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testRoomsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Rooms().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRoomsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	roomOne := &Room{}
	roomTwo := &Room{}
	if err = randomize.Struct(seed, roomOne, roomDBTypes, false, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}
	if err = randomize.Struct(seed, roomTwo, roomDBTypes, false, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = roomOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = roomTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Rooms().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRoomsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	roomOne := &Room{}
	roomTwo := &Room{}
	if err = randomize.Struct(seed, roomOne, roomDBTypes, false, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}
	if err = randomize.Struct(seed, roomTwo, roomDBTypes, false, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = roomOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = roomTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testRoomsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRoomsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(roomColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRoomToManyCompositesRooms(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Room
	var b, c CompositesRoom

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, compositesRoomDBTypes, false, compositesRoomColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, compositesRoomDBTypes, false, compositesRoomColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.RoomID = a.ID
	c.RoomID = a.ID

	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.CompositesRooms().All(tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.RoomID == b.RoomID {
			bFound = true
		}
		if v.RoomID == c.RoomID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := RoomSlice{&a}
	if err = a.L.LoadCompositesRooms(tx, false, (*[]*Room)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CompositesRooms); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.CompositesRooms = nil
	if err = a.L.LoadCompositesRooms(tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.CompositesRooms); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testRoomToManySessions(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Room
	var b, c Session

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, sessionDBTypes, false, sessionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, sessionDBTypes, false, sessionColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.RoomID, a.ID)
	queries.Assign(&c.RoomID, a.ID)
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Sessions().All(tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.RoomID, b.RoomID) {
			bFound = true
		}
		if queries.Equal(v.RoomID, c.RoomID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := RoomSlice{&a}
	if err = a.L.LoadSessions(tx, false, (*[]*Room)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Sessions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Sessions = nil
	if err = a.L.LoadSessions(tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Sessions); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testRoomToManyAddOpCompositesRooms(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Room
	var b, c, d, e CompositesRoom

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, roomDBTypes, false, strmangle.SetComplement(roomPrimaryKeyColumns, roomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*CompositesRoom{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, compositesRoomDBTypes, false, strmangle.SetComplement(compositesRoomPrimaryKeyColumns, compositesRoomColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*CompositesRoom{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddCompositesRooms(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.RoomID {
			t.Error("foreign key was wrong value", a.ID, first.RoomID)
		}
		if a.ID != second.RoomID {
			t.Error("foreign key was wrong value", a.ID, second.RoomID)
		}

		if first.R.Room != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Room != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.CompositesRooms[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.CompositesRooms[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.CompositesRooms().Count(tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testRoomToManyAddOpSessions(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Room
	var b, c, d, e Session

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, roomDBTypes, false, strmangle.SetComplement(roomPrimaryKeyColumns, roomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Session{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, sessionDBTypes, false, strmangle.SetComplement(sessionPrimaryKeyColumns, sessionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Session{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddSessions(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.RoomID) {
			t.Error("foreign key was wrong value", a.ID, first.RoomID)
		}
		if !queries.Equal(a.ID, second.RoomID) {
			t.Error("foreign key was wrong value", a.ID, second.RoomID)
		}

		if first.R.Room != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Room != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Sessions[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Sessions[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Sessions().Count(tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testRoomToManySetOpSessions(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Room
	var b, c, d, e Session

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, roomDBTypes, false, strmangle.SetComplement(roomPrimaryKeyColumns, roomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Session{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, sessionDBTypes, false, strmangle.SetComplement(sessionPrimaryKeyColumns, sessionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetSessions(tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Sessions().Count(tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetSessions(tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Sessions().Count(tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RoomID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RoomID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.RoomID) {
		t.Error("foreign key was wrong value", a.ID, d.RoomID)
	}
	if !queries.Equal(a.ID, e.RoomID) {
		t.Error("foreign key was wrong value", a.ID, e.RoomID)
	}

	if b.R.Room != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Room != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Room != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Room != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Sessions[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Sessions[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testRoomToManyRemoveOpSessions(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Room
	var b, c, d, e Session

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, roomDBTypes, false, strmangle.SetComplement(roomPrimaryKeyColumns, roomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Session{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, sessionDBTypes, false, strmangle.SetComplement(sessionPrimaryKeyColumns, sessionColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddSessions(tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Sessions().Count(tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveSessions(tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Sessions().Count(tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.RoomID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.RoomID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Room != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Room != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Room != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Room != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Sessions) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Sessions[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Sessions[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testRoomToOneGatewayUsingDefaultGateway(t *testing.T) {

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var local Room
	var foreign Gateway

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, roomDBTypes, false, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, gatewayDBTypes, false, gatewayColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Gateway struct: %s", err)
	}

	if err := foreign.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.DefaultGatewayID = foreign.ID
	if err := local.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.DefaultGateway().One(tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RoomSlice{&local}
	if err = local.L.LoadDefaultGateway(tx, false, (*[]*Room)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DefaultGateway == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.DefaultGateway = nil
	if err = local.L.LoadDefaultGateway(tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.DefaultGateway == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRoomToOneSetOpGatewayUsingDefaultGateway(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a Room
	var b, c Gateway

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, roomDBTypes, false, strmangle.SetComplement(roomPrimaryKeyColumns, roomColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, gatewayDBTypes, false, strmangle.SetComplement(gatewayPrimaryKeyColumns, gatewayColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, gatewayDBTypes, false, strmangle.SetComplement(gatewayPrimaryKeyColumns, gatewayColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Gateway{&b, &c} {
		err = a.SetDefaultGateway(tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.DefaultGateway != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.DefaultGatewayRooms[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.DefaultGatewayID != x.ID {
			t.Error("foreign key was wrong value", a.DefaultGatewayID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.DefaultGatewayID))
		reflect.Indirect(reflect.ValueOf(&a.DefaultGatewayID)).Set(zero)

		if err = a.Reload(tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.DefaultGatewayID != x.ID {
			t.Error("foreign key was wrong value", a.DefaultGatewayID, x.ID)
		}
	}
}

func testRoomsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testRoomsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RoomSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testRoomsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Rooms().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	roomDBTypes = map[string]string{`ID`: `bigint`, `Name`: `character varying`, `DefaultGatewayID`: `bigint`, `GatewayUID`: `integer`, `Secret`: `text`, `Disabled`: `boolean`, `Properties`: `jsonb`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `RemovedAt`: `timestamp with time zone`}
	_           = bytes.MinRead
)

func testRoomsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(roomPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(roomAllColumns) == len(roomPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, roomDBTypes, true, roomPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRoomsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(roomAllColumns) == len(roomPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Room{}
	if err = randomize.Struct(seed, o, roomDBTypes, true, roomColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, roomDBTypes, true, roomPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(roomAllColumns, roomPrimaryKeyColumns) {
		fields = roomAllColumns
	} else {
		fields = strmangle.SetComplement(
			roomAllColumns,
			roomPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RoomSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRoomsUpsert(t *testing.T) {
	t.Parallel()

	if len(roomAllColumns) == len(roomPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Room{}
	if err = randomize.Struct(seed, &o, roomDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Room: %s", err)
	}

	count, err := Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, roomDBTypes, false, roomPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Room struct: %s", err)
	}

	if err = o.Upsert(tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Room: %s", err)
	}

	count, err = Rooms().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
